// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistencia;

namespace Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211129020338_prrs")]
    partial class prrs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Dominio.Evaluar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Evaluacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("evaluacion");
                });

            modelBuilder.Entity("Dominio.Migrante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion_actual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion_electronica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha_nacimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero_identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero_telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais_origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Situacion_laboral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("migrantes");
                });

            modelBuilder.Entity("Dominio.Necesidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Alimentacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alojamiento_permanente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alojamiento_temporal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ayuda_legal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clasificacion_Alimentacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clasificacion_Alojamiento_permanente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clasificacion_Alojamiento_temporal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clasificacion_Ayuda_legal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clasificacion_Educacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clasificacion_Empleo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clasificacion_Salud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Educacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empleo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salud")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("necesidads");
                });
#pragma warning restore 612, 618
        }
    }
}
